api_version = "2025-04"

[[extensions]]
handle = "cart-pricing"
name = "cart-pricing"
type = "function"
uid = "30b30bed-683d-2dac-0933-3a1c35e2f3afab1b49f6"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "bash build.sh"
  path = "dist/function.wasm"
